version: '3.8'

services:
  postgres_db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres_db
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb
